services:
  # Your FastAPI search engine
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data  # Mount data directory for SQLite database
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0

  # Redis service for caching TF-IDF data and inverted index
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
